export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const RETRIEVED_MOVIES = 'RETRIEVED_MOVIES';
export const SEARCHED_MOVIES = 'SEARCHED_MOVIES';
export const GOT_INITIAL_LIST = 'GOT_INITIAL_lIST';
